#!/usr/bin/env python3

clear = '\033[H\033[2J'
red = '\033[0;31m'
yellow = '\033[0;33m'
blue = '\033[0;34m'
reset = '\033[030m'

print(clear)
print(red + 'Hello who are you' + reset)
name = input('> ')
print(red +  'nice to meet you '+  blue + name)
