#!/usr/bin/env python3 

import random as r
import colors as c
die = [None]

die.append('''
 -------
|•      |
|       |
|       |
 -------
 ''')

die.append('''
 -------
|•      |
|       |
|      •|
 -------
 ''')

die.append('''
 -------
| •     |
|   •   |
|     • |
 -------
 ''')

die.append('''
 -------
|•     •|
|       |
|•     •|
 -------
''')

die.append('''

 -------
  33 |•     •|
   34 |       |
    35 |•     •|
 -------

