#!/bin/sh
seconds=0
hundredths=0
minutes=0
hours=0
days=0
weeks=0
while true; do
  clear
  echo ${SOL_yellow}weeks:${SOL_reset}
  echo $weeks
  echo ${SOL_yellow}days:${SOL_reset}
  echo $days
  echo ${SOL_yellow}hours:${SOL_reset}
  echo $hours
  echo ${SOL_yellow}minutes:${SOL_reset}
  echo $minutes
  echo ${SOL_yellow}seconds:${SOL_reset}
  echo $seconds
  echo ${SOL_yellow}hundredths:${SOL_reset}
  echo $hundredths
  hundredths=`expr $hundredths + 1`
  if [ $hundredths -eq 100 ]
  then
    seconds=`expr $seconds + 1`
  fi
  if [ $seconds -eq 60 ]
  then
    minutes=`expr $minutes + 1`
    fi
  if [ $minutes -eq 60 ]
  then
    hours=`expr $hours + 1`
  fi
  if [ $hours -eq 24 ]
  then
    days=0`expr $days + 1`
  fi
  if [ $days -eq 7 ]
  then
    weeks=0`expr $weeks + 1`
  fi
  if [ $hundredths -eq 100 ]
  then
    hundredths=0`expr -  100`
  fi
  if [ $seconds -eq 60 ]
  then
    seconds=0`expr - 60`
  fi
  if [ $minutes -eq 60 ]
  then
    minutes=0`expr - 60`
  fi
  if [ $hours -eq 24 ]
  then
    hours=0`expr - 24`
  fi
  if [ $days -eq 7 ]
  then
    days=0`expr - 7`
  fi
  sleep 0.01
done
